// src/lib/curriculum.ts — Central curriculum data

import type { Phase, Exercise, Project } from "@/types";

export const PHASES: Phase[] = [
  {
    slug: "00-getting-started",
    title: "Getting Started",
    description: "Install Python, set up your editor, and run your first program.",
    order: 0,
    difficulty: "beginner",
    lessons: [
      {
        slug: "what-is-python",
        title: "What is Python?",
        description: "History, use cases, and why Python is a great first language.",
        phase: "00-getting-started",
        order: 1,
        difficulty: "beginner",
        prerequisites: [],
        tags: ["python", "intro", "history"],
        hasCode: true,
      },
      {
        slug: "install-python",
        title: "Install Python",
        description: "Download and install Python 3 on Windows, macOS, or Linux.",
        phase: "00-getting-started",
        order: 2,
        difficulty: "beginner",
        prerequisites: ["what-is-python"],
        tags: ["install", "setup"],
        hasCode: false,
      },
      {
        slug: "vscode-setup",
        title: "VS Code Setup",
        description: "Configure VS Code for Python development.",
        phase: "00-getting-started",
        order: 3,
        difficulty: "beginner",
        prerequisites: ["install-python"],
        tags: ["vscode", "editor", "setup"],
        hasCode: false,
      },
      {
        slug: "running-python",
        title: "Running Python Files",
        description: "Run .py files from the terminal and understand execution.",
        phase: "00-getting-started",
        order: 4,
        difficulty: "beginner",
        prerequisites: ["vscode-setup"],
        tags: ["terminal", "execution"],
        hasCode: true,
      },
      {
        slug: "python-repl",
        title: "The Python REPL",
        description: "Use the interactive Python shell to experiment with code.",
        phase: "00-getting-started",
        order: 5,
        difficulty: "beginner",
        prerequisites: ["running-python"],
        tags: ["repl", "interactive"],
        hasCode: true,
      },
      {
        slug: "virtual-environments",
        title: "Virtual Environments",
        description: "Create isolated Python environments for your projects.",
        phase: "00-getting-started",
        order: 6,
        difficulty: "beginner",
        prerequisites: ["python-repl"],
        tags: ["venv", "environments", "pip"],
        hasCode: true,
      },
      {
        slug: "pip",
        title: "pip — Package Manager",
        description: "Install and manage Python packages with pip.",
        phase: "00-getting-started",
        order: 7,
        difficulty: "beginner",
        prerequisites: ["virtual-environments"],
        tags: ["pip", "packages", "pypi"],
        hasCode: true,
      },
      {
        slug: "first-python-program",
        title: "Your First Python Program",
        description: "Write and run a complete Python program from scratch.",
        phase: "00-getting-started",
        order: 8,
        difficulty: "beginner",
        prerequisites: ["pip"],
        tags: ["print", "input", "variables", "beginner"],
        hasCode: true,
      },
    ],
  },
  {
    slug: "01-python-basics",
    title: "Python Basics",
    description: "Variables, data types, operators, and the building blocks of Python.",
    order: 1,
    difficulty: "beginner",
    lessons: [],
  },
  {
    slug: "02-control-flow",
    title: "Control Flow",
    description: "if/else, loops, and controlling the flow of your programs.",
    order: 2,
    difficulty: "beginner",
    lessons: [],
  },
  {
    slug: "03-functions",
    title: "Functions",
    description: "Define reusable blocks of code with parameters, return values, and more.",
    order: 3,
    difficulty: "beginner",
    lessons: [],
  },
  {
    slug: "04-data-structures",
    title: "Data Structures",
    description: "Lists, tuples, sets, and dictionaries — Python's built-in collections.",
    order: 4,
    difficulty: "beginner",
    lessons: [],
  },
  {
    slug: "05-strings",
    title: "Strings",
    description: "String manipulation, formatting, methods, and regular expressions.",
    order: 5,
    difficulty: "beginner",
    lessons: [],
  },
  {
    slug: "06-file-handling",
    title: "File Handling",
    description: "Read, write, and process files including CSV and JSON.",
    order: 6,
    difficulty: "intermediate",
    lessons: [],
  },
  {
    slug: "07-exceptions",
    title: "Exception Handling",
    description: "Handle errors gracefully with try/except and custom exceptions.",
    order: 7,
    difficulty: "intermediate",
    lessons: [],
  },
  {
    slug: "08-modules-packages",
    title: "Modules & Packages",
    description: "Organize code into modules and packages, use pip and PyPI.",
    order: 8,
    difficulty: "intermediate",
    lessons: [],
  },
  {
    slug: "09-object-oriented-programming",
    title: "Object-Oriented Programming",
    description: "Classes, objects, inheritance, polymorphism, and OOP design.",
    order: 9,
    difficulty: "intermediate",
    lessons: [],
  },
  {
    slug: "10-advanced-python",
    title: "Advanced Python",
    description: "Generators, decorators, context managers, typing, and Python internals.",
    order: 10,
    difficulty: "advanced",
    lessons: [],
  },
  {
    slug: "11-dsa",
    title: "Data Structures & Algorithms",
    description: "Arrays, linked lists, trees, graphs, and Big O analysis in Python.",
    order: 11,
    difficulty: "advanced",
    lessons: [],
  },
  {
    slug: "12-algorithms",
    title: "Algorithms",
    description: "Sorting, searching, dynamic programming, and algorithm patterns.",
    order: 12,
    difficulty: "advanced",
    lessons: [],
  },
  {
    slug: "13-testing",
    title: "Testing",
    description: "Unit testing, pytest, fixtures, mocking, and TDD.",
    order: 13,
    difficulty: "intermediate",
    lessons: [],
  },
  {
    slug: "14-databases",
    title: "Databases",
    description: "SQL, SQLite, PostgreSQL, SQLAlchemy ORM, and migrations.",
    order: 14,
    difficulty: "intermediate",
    lessons: [],
  },
  {
    slug: "15-api-development",
    title: "API Development",
    description: "HTTP, REST, JSON, authentication, and building APIs with Python.",
    order: 15,
    difficulty: "intermediate",
    lessons: [],
  },
  {
    slug: "16-fastapi",
    title: "FastAPI",
    description: "Build production-quality APIs with FastAPI, Pydantic, and OpenAPI.",
    order: 16,
    difficulty: "advanced",
    lessons: [],
  },
  {
    slug: "17-automation",
    title: "Automation",
    description: "Automate files, emails, web scraping, and build CLI tools.",
    order: 17,
    difficulty: "intermediate",
    lessons: [],
  },
  {
    slug: "18-data-python",
    title: "Python for Data",
    description: "NumPy, Pandas, Matplotlib, and data analysis with Python.",
    order: 18,
    difficulty: "intermediate",
    lessons: [],
  },
  {
    slug: "19-asynchronous-python",
    title: "Async Python",
    description: "asyncio, threading, multiprocessing, and concurrent programming.",
    order: 19,
    difficulty: "advanced",
    lessons: [],
  },
  {
    slug: "20-real-world-projects",
    title: "Real-World Projects",
    description: "Build complete, production-quality Python applications.",
    order: 20,
    difficulty: "advanced",
    lessons: [],
  },
];

export const EXERCISES: Exercise[] = [
  {
    slug: "hello-world",
    title: "Hello, World!",
    description: "Print Hello, World! to the terminal.",
    difficulty: "beginner",
    tags: ["print", "basics"],
    hints: ["Use the print() function"],
  },
  {
    slug: "sum-two-numbers",
    title: "Sum of Two Numbers",
    description: "Return the sum of two numbers.",
    difficulty: "beginner",
    tags: ["arithmetic", "functions"],
    hints: ["Use the + operator"],
  },
  {
    slug: "even-or-odd",
    title: "Even or Odd",
    description: 'Return "even" or "odd" for a given integer.',
    difficulty: "beginner",
    tags: ["modulo", "conditionals"],
    hints: ["Use the % operator"],
  },
  {
    slug: "reverse-string",
    title: "Reverse a String",
    description: "Return the reverse of a given string.",
    difficulty: "easy",
    tags: ["strings", "slicing"],
    hints: ["Python slicing supports a step of -1"],
  },
  {
    slug: "fizzbuzz",
    title: "FizzBuzz",
    description: "Classic FizzBuzz for numbers 1 through n.",
    difficulty: "easy",
    tags: ["loops", "conditionals", "modulo"],
    hints: ["Check divisibility by 15 first"],
  },
  {
    slug: "two-sum",
    title: "Two Sum",
    description: "Find two indices that add up to a target value.",
    difficulty: "interview",
    tags: ["hash-map", "arrays", "interview"],
    hints: ["A hash map gives O(n) time complexity"],
  },
];

export const PROJECTS: Project[] = [
  {
    slug: "01-number-guessing-game",
    title: "Number Guessing Game",
    description: "A CLI game where the player guesses a random number.",
    difficulty: "beginner",
    concepts: ["variables", "loops", "conditionals", "random", "input"],
    order: 1,
  },
];

// Derived counts — never hardcode these in UI
export const STATS = {
  phases: PHASES.length,
  lessons: PHASES.reduce((acc, p) => acc + p.lessons.length, 0),
  exercises: EXERCISES.length,
  projects: PROJECTS.length,
};
