// src/lib/curriculum.ts — Central curriculum data across all 21 Phases
import type { Phase, Exercise, Project } from "@/types";

export const PHASES: Phase[] = [
  /* ── 00. GETTING STARTED ───────────────────────────────────── */
  {
    slug: "00-getting-started",
    title: "Getting Started",
    description: "Install Python, set up your editor, and run your first program.",
    order: 0,
    difficulty: "beginner",
    lessons: [
      {
        slug: "what-is-python",
        title: "What is Python?",
        description: "History, use cases, and why Python is a great first language.",
        phase: "00-getting-started",
        order: 1,
        difficulty: "beginner",
        prerequisites: [],
        tags: ["python", "intro", "history"],
        hasCode: true,
      },
      {
        slug: "install-python",
        title: "Install Python",
        description: "Download and install Python 3 on Windows, macOS, or Linux.",
        phase: "00-getting-started",
        order: 2,
        difficulty: "beginner",
        prerequisites: ["what-is-python"],
        tags: ["install", "setup"],
        hasCode: false,
      },
      {
        slug: "vscode-setup",
        title: "VS Code Setup",
        description: "Configure VS Code for Python development.",
        phase: "00-getting-started",
        order: 3,
        difficulty: "beginner",
        prerequisites: ["install-python"],
        tags: ["vscode", "editor", "setup"],
        hasCode: false,
      },
      {
        slug: "running-python",
        title: "Running Python Files",
        description: "Run .py files from the terminal and understand execution.",
        phase: "00-getting-started",
        order: 4,
        difficulty: "beginner",
        prerequisites: ["vscode-setup"],
        tags: ["terminal", "execution"],
        hasCode: true,
      },
      {
        slug: "python-repl",
        title: "The Python REPL",
        description: "Use the interactive Python shell to experiment with code.",
        phase: "00-getting-started",
        order: 5,
        difficulty: "beginner",
        prerequisites: ["running-python"],
        tags: ["repl", "interactive"],
        hasCode: true,
      },
      {
        slug: "virtual-environments",
        title: "Virtual Environments",
        description: "Create isolated Python environments for your projects.",
        phase: "00-getting-started",
        order: 6,
        difficulty: "beginner",
        prerequisites: ["python-repl"],
        tags: ["venv", "environments", "pip"],
        hasCode: true,
      },
      {
        slug: "pip",
        title: "pip — Package Manager",
        description: "Install and manage Python packages with pip.",
        phase: "00-getting-started",
        order: 7,
        difficulty: "beginner",
        prerequisites: ["virtual-environments"],
        tags: ["pip", "packages", "pypi"],
        hasCode: true,
      },
      {
        slug: "first-python-program",
        title: "Your First Python Program",
        description: "Write and run a complete Python program from scratch.",
        phase: "00-getting-started",
        order: 8,
        difficulty: "beginner",
        prerequisites: ["pip"],
        tags: ["print", "input", "variables", "beginner"],
        hasCode: true,
      },
    ],
  },

  /* ── 01. PYTHON BASICS ─────────────────────────────────────── */
  {
    slug: "01-python-basics",
    title: "Python Basics",
    description: "Variables, data types, operators, and the building blocks of Python.",
    order: 1,
    difficulty: "beginner",
    lessons: [
      {
        slug: "variables-and-assignment",
        title: "Variables and Assignment",
        description: "How Python names references to objects in heap memory.",
        phase: "01-python-basics",
        order: 1,
        difficulty: "beginner",
        prerequisites: ["first-python-program"],
        tags: ["variables", "assignment", "pointers"],
        hasCode: true,
      },
      {
        slug: "data-types",
        title: "Primitive Data Types",
        description: "Integers, floats, booleans, strings, and NoneType.",
        phase: "01-python-basics",
        order: 2,
        difficulty: "beginner",
        prerequisites: ["variables-and-assignment"],
        tags: ["types", "int", "float", "bool", "none"],
        hasCode: true,
      },
      {
        slug: "numbers-and-math",
        title: "Numbers and Arithmetic",
        description: "Operators, precedence, integer division, modulo, and math module.",
        phase: "01-python-basics",
        order: 3,
        difficulty: "beginner",
        prerequisites: ["data-types"],
        tags: ["math", "arithmetic", "modulo"],
        hasCode: true,
      },
      {
        slug: "type-conversion",
        title: "Type Casting and Conversion",
        description: "Explicit and implicit conversion between int, str, float, and bool.",
        phase: "01-python-basics",
        order: 4,
        difficulty: "beginner",
        prerequisites: ["numbers-and-math"],
        tags: ["casting", "conversion", "type"],
        hasCode: true,
      },
      {
        slug: "input-output-formatting",
        title: "User Input and Console Output",
        description: "Reading input, printing formatted output, and escaping characters.",
        phase: "01-python-basics",
        order: 5,
        difficulty: "beginner",
        prerequisites: ["type-conversion"],
        tags: ["io", "input", "print", "formatting"],
        hasCode: true,
      },
    ],
  },

  /* ── 02. CONTROL FLOW ──────────────────────────────────────── */
  {
    slug: "02-control-flow",
    title: "Control Flow",
    description: "if/else, loops, and controlling the execution path of your programs.",
    order: 2,
    difficulty: "beginner",
    lessons: [
      {
        slug: "conditional-statements",
        title: "If, Elif, and Else",
        description: "Branching execution paths based on boolean conditions.",
        phase: "02-control-flow",
        order: 1,
        difficulty: "beginner",
        prerequisites: ["input-output-formatting"],
        tags: ["if", "elif", "else", "branching"],
        hasCode: true,
      },
      {
        slug: "comparison-logical-operators",
        title: "Comparison & Logical Operators",
        description: "and, or, not, is, in, and short-circuit evaluation.",
        phase: "02-control-flow",
        order: 2,
        difficulty: "beginner",
        prerequisites: ["conditional-statements"],
        tags: ["logic", "operators", "short-circuit"],
        hasCode: true,
      },
      {
        slug: "while-loops",
        title: "While Loops and Sentinel Conditions",
        description: "Iterating until conditions change and preventing infinite loops.",
        phase: "02-control-flow",
        order: 3,
        difficulty: "beginner",
        prerequisites: ["comparison-logical-operators"],
        tags: ["while", "loops", "iteration"],
        hasCode: true,
      },
      {
        slug: "for-loops-and-range",
        title: "For Loops and range()",
        description: "Iterating over sequences, step ranges, and enumerate().",
        phase: "02-control-flow",
        order: 4,
        difficulty: "beginner",
        prerequisites: ["while-loops"],
        tags: ["for", "range", "enumerate"],
        hasCode: true,
      },
      {
        slug: "break-continue-pass",
        title: "Break, Continue, and Pass",
        description: "Controlling loop iterations and writing stub blocks.",
        phase: "02-control-flow",
        order: 5,
        difficulty: "beginner",
        prerequisites: ["for-loops-and-range"],
        tags: ["break", "continue", "pass"],
        hasCode: true,
      },
      {
        slug: "pattern-matching-match-case",
        title: "Structural Pattern Matching (match-case)",
        description: "Python 3.10+ pattern matching for clean state dispatch.",
        phase: "02-control-flow",
        order: 6,
        difficulty: "beginner",
        prerequisites: ["break-continue-pass"],
        tags: ["pattern-matching", "match-case", "python310"],
        hasCode: true,
      },
    ],
  },

  /* ── 03. FUNCTIONS ─────────────────────────────────────────── */
  {
    slug: "03-functions",
    title: "Functions",
    description: "Define reusable blocks of code with parameters, return values, and scopes.",
    order: 3,
    difficulty: "beginner",
    lessons: [
      {
        slug: "defining-calling-functions",
        title: "Defining & Calling Functions",
        description: "The def statement, calling conventions, and return values.",
        phase: "03-functions",
        order: 1,
        difficulty: "beginner",
        prerequisites: ["pattern-matching-match-case"],
        tags: ["def", "functions", "return"],
        hasCode: true,
      },
      {
        slug: "parameters-and-arguments",
        title: "Positional vs Keyword Arguments",
        description: "Default values, keyword-only parameters, and ordering rules.",
        phase: "03-functions",
        order: 2,
        difficulty: "beginner",
        prerequisites: ["defining-calling-functions"],
        tags: ["arguments", "parameters", "kwargs"],
        hasCode: true,
      },
      {
        slug: "variable-length-arguments",
        title: "*args and **kwargs",
        description: "Arbitrary argument packing and dictionary keyword unpacking.",
        phase: "03-functions",
        order: 3,
        difficulty: "beginner",
        prerequisites: ["parameters-and-arguments"],
        tags: ["args", "kwargs", "unpacking"],
        hasCode: true,
      },
      {
        slug: "scope-and-closures",
        title: "LEGB Scope & Closures",
        description: "Local, Enclosing, Global, Built-in scopes and nonlocal keyword.",
        phase: "03-functions",
        order: 4,
        difficulty: "beginner",
        prerequisites: ["variable-length-arguments"],
        tags: ["scope", "legb", "closures", "global"],
        hasCode: true,
      },
      {
        slug: "lambda-and-functional-helpers",
        title: "Lambda Expressions, Map & Filter",
        description: "Anonymous inline functions and functional transformations.",
        phase: "03-functions",
        order: 5,
        difficulty: "beginner",
        prerequisites: ["scope-and-closures"],
        tags: ["lambda", "map", "filter", "functional"],
        hasCode: true,
      },
      {
        slug: "type-hints-and-docstrings",
        title: "Type Annotations and Docstrings",
        description: "PEP 484 type hints, typing module, and PEP 257 docstrings.",
        phase: "03-functions",
        order: 6,
        difficulty: "beginner",
        prerequisites: ["lambda-and-functional-helpers"],
        tags: ["type-hints", "docstrings", "typing"],
        hasCode: true,
      },
    ],
  },

  /* ── 04. DATA STRUCTURES ───────────────────────────────────── */
  {
    slug: "04-data-structures",
    title: "Data Structures",
    description: "Lists, tuples, sets, and dictionaries — Python's built-in collections.",
    order: 4,
    difficulty: "beginner",
    lessons: [
      {
        slug: "lists-and-operations",
        title: "Lists & Array Operations",
        description: "Indexing, slicing, appending, inserting, and in-place sorting.",
        phase: "04-data-structures",
        order: 1,
        difficulty: "beginner",
        prerequisites: ["type-hints-and-docstrings"],
        tags: ["lists", "indexing", "slicing", "mutability"],
        hasCode: true,
      },
      {
        slug: "tuples-and-immutability",
        title: "Tuples & NamedTuples",
        description: "Immutable sequences, tuple unpacking, and typing.NamedTuple.",
        phase: "04-data-structures",
        order: 2,
        difficulty: "beginner",
        prerequisites: ["lists-and-operations"],
        tags: ["tuples", "immutability", "unpacking"],
        hasCode: true,
      },
      {
        slug: "dictionaries-and-hashmaps",
        title: "Dictionaries & Key-Value Lookup",
        description: "O(1) hashing, keys(), values(), items(), and get() defaults.",
        phase: "04-data-structures",
        order: 3,
        difficulty: "beginner",
        prerequisites: ["tuples-and-immutability"],
        tags: ["dict", "hashmap", "keys", "values"],
        hasCode: true,
      },
      {
        slug: "sets-and-set-theory",
        title: "Sets and Set Theory",
        description: "Unique elements, unions, intersections, and set operations.",
        phase: "04-data-structures",
        order: 4,
        difficulty: "beginner",
        prerequisites: ["dictionaries-and-hashmaps"],
        tags: ["sets", "union", "intersection"],
        hasCode: true,
      },
      {
        slug: "comprehensions",
        title: "List, Dict, and Set Comprehensions",
        description: "Idiomatic declarative construction of collections in Python.",
        phase: "04-data-structures",
        order: 5,
        difficulty: "beginner",
        prerequisites: ["sets-and-set-theory"],
        tags: ["comprehensions", "idiomatic", "loops"],
        hasCode: true,
      },
    ],
  },

  /* ── 05. STRINGS ───────────────────────────────────────────── */
  {
    slug: "05-strings",
    title: "Strings",
    description: "String manipulation, formatting, methods, and regular expressions.",
    order: 5,
    difficulty: "beginner",
    lessons: [
      {
        slug: "string-slicing-indexing",
        title: "String Slicing & Indexing",
        description: "Positive and negative indexing, stride step, and reverse slicing.",
        phase: "05-strings",
        order: 1,
        difficulty: "beginner",
        prerequisites: ["comprehensions"],
        tags: ["strings", "slicing", "indexing"],
        hasCode: true,
      },
      {
        slug: "string-methods",
        title: "Built-in String Methods",
        description: "split, join, strip, replace, startswith, find, and partition.",
        phase: "05-strings",
        order: 2,
        difficulty: "beginner",
        prerequisites: ["string-slicing-indexing"],
        tags: ["methods", "split", "join", "strip"],
        hasCode: true,
      },
      {
        slug: "f-strings-formatting",
        title: "f-Strings & String Interpolation",
        description: "Advanced format specifiers, alignment, decimals, and debug expressions.",
        phase: "05-strings",
        order: 3,
        difficulty: "beginner",
        prerequisites: ["string-methods"],
        tags: ["fstrings", "formatting", "interpolation"],
        hasCode: true,
      },
      {
        slug: "unicode-and-encoding",
        title: "Unicode, ASCII & Bytes",
        description: "UTF-8 encoding, bytes vs str, and bytearrays in Python.",
        phase: "05-strings",
        order: 4,
        difficulty: "beginner",
        prerequisites: ["f-strings-formatting"],
        tags: ["unicode", "utf8", "bytes", "encoding"],
        hasCode: true,
      },
      {
        slug: "regular-expressions-re",
        title: "Regular Expressions with re Module",
        description: "Pattern compilation, matching, search, groups, and substitution.",
        phase: "05-strings",
        order: 5,
        difficulty: "beginner",
        prerequisites: ["unicode-and-encoding"],
        tags: ["regex", "re", "pattern-matching"],
        hasCode: true,
      },
    ],
  },

  /* ── 06. FILE HANDLING ─────────────────────────────────────── */
  {
    slug: "06-file-handling",
    title: "File Handling",
    description: "Read, write, and process files including CSV and JSON.",
    order: 6,
    difficulty: "intermediate",
    lessons: [
      {
        slug: "reading-writing-text-files",
        title: "Reading & Writing Text Files",
        description: "open(), read(), readlines(), write(), and file buffering.",
        phase: "06-file-handling",
        order: 1,
        difficulty: "intermediate",
        prerequisites: ["regular-expressions-re"],
        tags: ["files", "io", "open", "read", "write"],
        hasCode: true,
      },
      {
        slug: "with-statement-context-managers",
        title: "The with Statement & Safe File Closing",
        description: "Automatic cleanup, file descriptors, and resource management.",
        phase: "06-file-handling",
        order: 2,
        difficulty: "intermediate",
        prerequisites: ["reading-writing-text-files"],
        tags: ["with", "context-manager", "cleanup"],
        hasCode: true,
      },
      {
        slug: "csv-file-processing",
        title: "CSV Parsing with csv Module",
        description: "csv.reader, csv.writer, and DictReader for structured tabular data.",
        phase: "06-file-handling",
        order: 3,
        difficulty: "intermediate",
        prerequisites: ["with-statement-context-managers"],
        tags: ["csv", "dictreader", "tabular"],
        hasCode: true,
      },
      {
        slug: "json-serialization",
        title: "JSON Serialization with json Module",
        description: "json.loads, json.dumps, json.load, json.dump, and custom encoders.",
        phase: "06-file-handling",
        order: 4,
        difficulty: "intermediate",
        prerequisites: ["csv-file-processing"],
        tags: ["json", "serialization", "deserialization"],
        hasCode: true,
      },
      {
        slug: "pathlib-modern-filesystem",
        title: "Modern Path Handling with pathlib",
        description: "Path objects, directory traversal, globbing, and cross-platform paths.",
        phase: "06-file-handling",
        order: 5,
        difficulty: "intermediate",
        prerequisites: ["json-serialization"],
        tags: ["pathlib", "paths", "glob", "filesystem"],
        hasCode: true,
      },
    ],
  },

  /* ── 07. EXCEPTION HANDLING ────────────────────────────────── */
  {
    slug: "07-exceptions",
    title: "Exception Handling",
    description: "Handle errors gracefully with try/except and custom exceptions.",
    order: 7,
    difficulty: "intermediate",
    lessons: [
      {
        slug: "try-except-else-finally",
        title: "try, except, else, and finally",
        description: "Structured error trapping, cleanup execution, and catch ordering.",
        phase: "07-exceptions",
        order: 1,
        difficulty: "intermediate",
        prerequisites: ["pathlib-modern-filesystem"],
        tags: ["try", "except", "finally", "errors"],
        hasCode: true,
      },
      {
        slug: "builtin-exception-hierarchy",
        title: "Python's Built-in Exception Hierarchy",
        description: "BaseException, Exception, ValueError, TypeError, KeyError, IndexError.",
        phase: "07-exceptions",
        order: 2,
        difficulty: "intermediate",
        prerequisites: ["try-except-else-finally"],
        tags: ["exceptions", "hierarchy", "valueerror"],
        hasCode: true,
      },
      {
        slug: "raising-and-chaining-exceptions",
        title: "Raising Exceptions & raise from",
        description: "Explicit raise statements, exception chaining, and __cause__.",
        phase: "07-exceptions",
        order: 3,
        difficulty: "intermediate",
        prerequisites: ["builtin-exception-hierarchy"],
        tags: ["raise", "chaining", "cause"],
        hasCode: true,
      },
      {
        slug: "custom-exception-classes",
        title: "Authoring Custom Exception Classes",
        description: "Subclassing Exception and designing structured domain errors.",
        phase: "07-exceptions",
        order: 4,
        difficulty: "intermediate",
        prerequisites: ["raising-and-chaining-exceptions"],
        tags: ["custom-exceptions", "oop", "domain-errors"],
        hasCode: true,
      },
      {
        slug: "traceback-and-logging-errors",
        title: "Traceback Inspection & logging",
        description: "Capturing stack traces and logging structured error details.",
        phase: "07-exceptions",
        order: 5,
        difficulty: "intermediate",
        prerequisites: ["custom-exception-classes"],
        tags: ["traceback", "logging", "debugging"],
        hasCode: true,
      },
    ],
  },

  /* ── 08. MODULES & PACKAGES ────────────────────────────────── */
  {
    slug: "08-modules-packages",
    title: "Modules & Packages",
    description: "Organize code into modules and packages, use pip and PyPI.",
    order: 8,
    difficulty: "intermediate",
    lessons: [
      {
        slug: "import-mechanics-and-sys-path",
        title: "Import Mechanics & sys.path",
        description: "How Python resolves modules, module caching in sys.modules.",
        phase: "08-modules-packages",
        order: 1,
        difficulty: "intermediate",
        prerequisites: ["traceback-and-logging-errors"],
        tags: ["import", "sys.path", "sys.modules"],
        hasCode: true,
      },
      {
        slug: "main-and-script-execution",
        title: "if __name__ == '__main__'",
        description: "Writing dual-purpose files that act as both modules and executable scripts.",
        phase: "08-modules-packages",
        order: 2,
        difficulty: "intermediate",
        prerequisites: ["import-mechanics-and-sys-path"],
        tags: ["__name__", "__main__", "scripts"],
        hasCode: true,
      },
      {
        slug: "creating-packages-and-init",
        title: "Creating Packages & __init__.py",
        description: "Package hierarchies, __all__ exports, and relative imports.",
        phase: "08-modules-packages",
        order: 3,
        difficulty: "intermediate",
        prerequisites: ["main-and-script-execution"],
        tags: ["packages", "__init__", "__all__"],
        hasCode: true,
      },
      {
        slug: "modern-packaging-pyproject",
        title: "Modern Packaging with pyproject.toml",
        description: "PEP 517/621, build backends (hatchling/flit), and publishing to PyPI.",
        phase: "08-modules-packages",
        order: 4,
        difficulty: "intermediate",
        prerequisites: ["creating-packages-and-init"],
        tags: ["pyproject", "packaging", "pypi"],
        hasCode: true,
      },
    ],
  },

  /* ── 09. OBJECT-ORIENTED PROGRAMMING ───────────────────────── */
  {
    slug: "09-object-oriented-programming",
    title: "Object-Oriented Programming",
    description: "Classes, objects, inheritance, composition, and reusable OOP design.",
    order: 9,
    difficulty: "intermediate",
    lessons: [
      {
        slug: "classes-and-objects",
        title: "Classes & Objects",
        description: "Class definitions, instantiation, and object identity in Python.",
        phase: "09-object-oriented-programming",
        order: 1,
        difficulty: "intermediate",
        prerequisites: ["modern-packaging-pyproject"],
        tags: ["classes", "objects", "oop"],
        hasCode: true,
      },
      {
        slug: "init-and-instance-state",
        title: "__init__ and Instance State",
        description: "Constructor initialization, self reference, and instance attributes.",
        phase: "09-object-oriented-programming",
        order: 2,
        difficulty: "intermediate",
        prerequisites: ["classes-and-objects"],
        tags: ["__init__", "self", "state"],
        hasCode: true,
      },
      {
        slug: "instance-class-static-methods",
        title: "Instance, Class & Static Methods",
        description: "@classmethod, @staticmethod, and cls vs self conventions.",
        phase: "09-object-oriented-programming",
        order: 3,
        difficulty: "intermediate",
        prerequisites: ["init-and-instance-state"],
        tags: ["classmethod", "staticmethod", "decorators"],
        hasCode: true,
      },
      {
        slug: "encapsulation-and-access",
        title: "Encapsulation & Name Mangling",
        description: "Public, protected (_), and private (__) variables in Python.",
        phase: "09-object-oriented-programming",
        order: 4,
        difficulty: "intermediate",
        prerequisites: ["instance-class-static-methods"],
        tags: ["encapsulation", "name-mangling", "privacy"],
        hasCode: true,
      },
      {
        slug: "inheritance-and-super",
        title: "Inheritance and super()",
        description: "Single and multiple inheritance, method overriding, and super().",
        phase: "09-object-oriented-programming",
        order: 5,
        difficulty: "intermediate",
        prerequisites: ["encapsulation-and-access"],
        tags: ["inheritance", "super", "polymorphism"],
        hasCode: true,
      },
      {
        slug: "composition-over-inheritance",
        title: "Composition & Delegation",
        description: "Favoring object composition over deep inheritance hierarchies.",
        phase: "09-object-oriented-programming",
        order: 6,
        difficulty: "intermediate",
        prerequisites: ["inheritance-and-super"],
        tags: ["composition", "delegation", "design"],
        hasCode: true,
      },
      {
        slug: "polymorphism-and-duck-typing",
        title: "Polymorphism & Duck Typing",
        description: "'If it walks like a duck' — protocols and interfaces in Python.",
        phase: "09-object-oriented-programming",
        order: 7,
        difficulty: "intermediate",
        prerequisites: ["composition-over-inheritance"],
        tags: ["polymorphism", "duck-typing", "protocols"],
        hasCode: true,
      },
      {
        slug: "abstract-base-classes",
        title: "Abstract Base Classes (abc)",
        description: "Enforcing method implementation with @abstractmethod and ABC.",
        phase: "09-object-oriented-programming",
        order: 8,
        difficulty: "intermediate",
        prerequisites: ["polymorphism-and-duck-typing"],
        tags: ["abc", "abstractmethod", "interfaces"],
        hasCode: true,
      },
      {
        slug: "dunder-methods",
        title: "Magic & Dunder Methods",
        description: "__str__, __repr__, __len__, __eq__, __add__, and __getitem__.",
        phase: "09-object-oriented-programming",
        order: 9,
        difficulty: "intermediate",
        prerequisites: ["abstract-base-classes"],
        tags: ["dunder", "magic-methods", "operator-overloading"],
        hasCode: true,
      },
      {
        slug: "properties-and-descriptors",
        title: "Properties (@property) & Descriptors",
        description: "Getters, setters, deleters, and the descriptor protocol (__get__, __set__).",
        phase: "09-object-oriented-programming",
        order: 10,
        difficulty: "intermediate",
        prerequisites: ["dunder-methods"],
        tags: ["property", "descriptors", "getters"],
        hasCode: true,
      },
      {
        slug: "oop-design-patterns",
        title: "OOP Design Patterns in Python",
        description: "Factory, Singleton, Strategy, Observer, and Adapter patterns.",
        phase: "09-object-oriented-programming",
        order: 11,
        difficulty: "intermediate",
        prerequisites: ["properties-and-descriptors"],
        tags: ["design-patterns", "factory", "singleton", "observer"],
        hasCode: true,
      },
    ],
  },

  /* ── 10. ADVANCED PYTHON ───────────────────────────────────── */
  {
    slug: "10-advanced-python",
    title: "Advanced Python",
    description: "Generators, decorators, context managers, typing, and Python internals.",
    order: 10,
    difficulty: "advanced",
    lessons: [
      {
        slug: "iterators-and-iterables",
        title: "Iterators, Iterables & __iter__",
        description: "The iteration protocol, __next__, StopIteration, and iter().",
        phase: "10-advanced-python",
        order: 1,
        difficulty: "advanced",
        prerequisites: ["oop-design-patterns"],
        tags: ["iterators", "iterables", "protocol"],
        hasCode: true,
      },
      {
        slug: "generators-and-yield",
        title: "Generators, yield & yield from",
        description: "Memory-efficient lazy streaming and generator delegation.",
        phase: "10-advanced-python",
        order: 2,
        difficulty: "advanced",
        prerequisites: ["iterators-and-iterables"],
        tags: ["generators", "yield", "streaming"],
        hasCode: true,
      },
      {
        slug: "custom-decorators",
        title: "Function & Class Decorators",
        description: "Higher-order functions, functools.wraps, and parameterized decorators.",
        phase: "10-advanced-python",
        order: 3,
        difficulty: "advanced",
        prerequisites: ["generators-and-yield"],
        tags: ["decorators", "wraps", "closures"],
        hasCode: true,
      },
      {
        slug: "context-managers-contextlib",
        title: "Context Managers & contextlib",
        description: "__enter__, __exit__, and writing context managers with @contextmanager.",
        phase: "10-advanced-python",
        order: 4,
        difficulty: "advanced",
        prerequisites: ["custom-decorators"],
        tags: ["context-managers", "contextlib", "enter-exit"],
        hasCode: true,
      },
      {
        slug: "metaclasses-and-type-creation",
        title: "Metaclasses & Dynamic Type Creation",
        description: "type(), __new__, metaclass inheritance, and class validation.",
        phase: "10-advanced-python",
        order: 5,
        difficulty: "advanced",
        prerequisites: ["context-managers-contextlib"],
        tags: ["metaclasses", "type", "__new__"],
        hasCode: true,
      },
      {
        slug: "cpython-internals-and-bytecode",
        title: "CPython Internals, GIL & Bytecode",
        description: "PyObject struct, Global Interpreter Lock, dis module, and garbage collection.",
        phase: "10-advanced-python",
        order: 6,
        difficulty: "advanced",
        prerequisites: ["metaclasses-and-type-creation"],
        tags: ["cpython", "gil", "bytecode", "garbage-collection"],
        hasCode: true,
      },
    ],
  },

  /* ── 11. DATA STRUCTURES & ALGORITHMS ──────────────────────── */
  {
    slug: "11-dsa",
    title: "Data Structures & Algorithms",
    description: "Arrays, linked lists, trees, graphs, and Big O analysis in Python.",
    order: 11,
    difficulty: "advanced",
    lessons: [
      {
        slug: "big-o-notation-and-complexity",
        title: "Big O Notation & Complexity Analysis",
        description: "Time and space complexity, amortized analysis, and asymptotic bounds.",
        phase: "11-dsa",
        order: 1,
        difficulty: "advanced",
        prerequisites: ["cpython-internals-and-bytecode"],
        tags: ["big-o", "complexity", "time-space"],
        hasCode: true,
      },
      {
        slug: "dynamic-arrays-internals",
        title: "Dynamic Arrays & Python Lists",
        description: "Contiguous memory, resizing amortized O(1), and array allocations.",
        phase: "11-dsa",
        order: 2,
        difficulty: "advanced",
        prerequisites: ["big-o-notation-and-complexity"],
        tags: ["arrays", "dynamic-arrays", "memory"],
        hasCode: true,
      },
      {
        slug: "singly-doubly-linked-lists",
        title: "Singly and Doubly Linked Lists",
        description: "Node pointers, insertions, deletions, and cycle detection.",
        phase: "11-dsa",
        order: 3,
        difficulty: "advanced",
        prerequisites: ["dynamic-arrays-internals"],
        tags: ["linked-lists", "nodes", "pointers"],
        hasCode: true,
      },
      {
        slug: "stacks-and-queues",
        title: "Stacks, Queues, and Deques",
        description: "LIFO, FIFO, collections.deque, and monotonic stack patterns.",
        phase: "11-dsa",
        order: 4,
        difficulty: "advanced",
        prerequisites: ["singly-doubly-linked-lists"],
        tags: ["stacks", "queues", "deque"],
        hasCode: true,
      },
      {
        slug: "hash-tables-and-collisions",
        title: "Hash Tables & Collision Resolution",
        description: "Hash functions, open addressing, chaining, and dict implementation.",
        phase: "11-dsa",
        order: 5,
        difficulty: "advanced",
        prerequisites: ["stacks-and-queues"],
        tags: ["hash-tables", "collisions", "hashing"],
        hasCode: true,
      },
      {
        slug: "binary-search-trees",
        title: "Binary Trees & BST Operations",
        description: "Node structures, BST search, insertion, deletion, and tree traversals.",
        phase: "11-dsa",
        order: 6,
        difficulty: "advanced",
        prerequisites: ["hash-tables-and-collisions"],
        tags: ["trees", "bst", "traversals"],
        hasCode: true,
      },
      {
        slug: "graphs-representations",
        title: "Graphs: Adjacency Lists & Matrices",
        description: "Directed, undirected, weighted graphs and network representations.",
        phase: "11-dsa",
        order: 7,
        difficulty: "advanced",
        prerequisites: ["binary-search-trees"],
        tags: ["graphs", "adjacency-list", "networks"],
        hasCode: true,
      },
    ],
  },

  /* ── 12. ALGORITHMS ────────────────────────────────────────── */
  {
    slug: "12-algorithms",
    title: "Algorithms",
    description: "Sorting, searching, dynamic programming, and algorithm patterns.",
    order: 12,
    difficulty: "advanced",
    lessons: [
      {
        slug: "binary-search-pattern",
        title: "Binary Search & Two Pointers",
        description: "O(log n) boundary search and two-pointer pointer mechanics.",
        phase: "12-algorithms",
        order: 1,
        difficulty: "advanced",
        prerequisites: ["graphs-representations"],
        tags: ["binary-search", "two-pointers"],
        hasCode: true,
      },
      {
        slug: "sorting-algorithms",
        title: "Sorting: Merge Sort, Quick Sort & Timsort",
        description: "Divide and conquer sorting, stability, and Python's built-in Timsort.",
        phase: "12-algorithms",
        order: 2,
        difficulty: "advanced",
        prerequisites: ["binary-search-pattern"],
        tags: ["sorting", "mergesort", "quicksort", "timsort"],
        hasCode: true,
      },
      {
        slug: "recursion-and-backtracking",
        title: "Recursion & Backtracking",
        description: "Call stack mechanics, base cases, permutations, and subsets.",
        phase: "12-algorithms",
        order: 3,
        difficulty: "advanced",
        prerequisites: ["sorting-algorithms"],
        tags: ["recursion", "backtracking", "call-stack"],
        hasCode: true,
      },
      {
        slug: "bfs-dfs-graph-algorithms",
        title: "Graph Traversal: BFS & DFS",
        description: "Breadth-first queue exploration, depth-first recursion, and topological sort.",
        phase: "12-algorithms",
        order: 4,
        difficulty: "advanced",
        prerequisites: ["recursion-and-backtracking"],
        tags: ["bfs", "dfs", "topological-sort"],
        hasCode: true,
      },
      {
        slug: "greedy-algorithms",
        title: "Greedy Algorithms",
        description: "Locally optimal choices, interval scheduling, and Huffman coding.",
        phase: "12-algorithms",
        order: 5,
        difficulty: "advanced",
        prerequisites: ["bfs-dfs-graph-algorithms"],
        tags: ["greedy", "intervals", "optimization"],
        hasCode: true,
      },
      {
        slug: "dynamic-programming-fundamentals",
        title: "Dynamic Programming: Memoization & Tabulation",
        description: "Overlapping subproblems, optimal substructure, and 1D/2D DP tables.",
        phase: "12-algorithms",
        order: 6,
        difficulty: "advanced",
        prerequisites: ["greedy-algorithms"],
        tags: ["dp", "memoization", "tabulation"],
        hasCode: true,
      },
    ],
  },

  /* ── 13. TESTING ───────────────────────────────────────────── */
  {
    slug: "13-testing",
    title: "Testing",
    description: "Unit testing, pytest, fixtures, mocking, and TDD.",
    order: 13,
    difficulty: "intermediate",
    lessons: [
      {
        slug: "unit-testing-principles",
        title: "Unit Testing with unittest & pytest",
        description: "Writing assertions, test runners, and structuring test directories.",
        phase: "13-testing",
        order: 1,
        difficulty: "intermediate",
        prerequisites: ["dynamic-programming-fundamentals"],
        tags: ["testing", "pytest", "assertions"],
        hasCode: true,
      },
      {
        slug: "pytest-fixtures-and-scopes",
        title: "pytest Fixtures & Setup/Teardown",
        description: "@pytest.fixture, autouse, fixture scopes (function, module, session).",
        phase: "13-testing",
        order: 2,
        difficulty: "intermediate",
        prerequisites: ["unit-testing-principles"],
        tags: ["pytest", "fixtures", "teardown"],
        hasCode: true,
      },
      {
        slug: "mocking-and-monkeypatching",
        title: "Mocking with unittest.mock",
        description: "Mock, MagicMock, patch(), monkeypatch, and isolating external APIs.",
        phase: "13-testing",
        order: 3,
        difficulty: "intermediate",
        prerequisites: ["pytest-fixtures-and-scopes"],
        tags: ["mock", "patch", "monkeypatch"],
        hasCode: true,
      },
      {
        slug: "parametrized-testing-and-coverage",
        title: "Parametrized Tests & Code Coverage",
        description: "@pytest.mark.parametrize, pytest-cov, and branch coverage reports.",
        phase: "13-testing",
        order: 4,
        difficulty: "intermediate",
        prerequisites: ["mocking-and-monkeypatching"],
        tags: ["parametrize", "coverage", "reports"],
        hasCode: true,
      },
    ],
  },

  /* ── 14. DATABASES ─────────────────────────────────────────── */
  {
    slug: "14-databases",
    title: "Databases",
    description: "SQL, SQLite, PostgreSQL, SQLAlchemy ORM, and migrations.",
    order: 14,
    difficulty: "intermediate",
    lessons: [
      {
        slug: "relational-sql-fundamentals",
        title: "SQL Fundamentals & Relational Schema",
        description: "SELECT, INSERT, UPDATE, DELETE, JOINs, foreign keys, and indexes.",
        phase: "14-databases",
        order: 1,
        difficulty: "intermediate",
        prerequisites: ["parametrized-testing-and-coverage"],
        tags: ["sql", "relational", "schema", "joins"],
        hasCode: true,
      },
      {
        slug: "sqlite3-with-python",
        title: "SQLite3 in Python",
        description: "sqlite3 module, parameterized queries (SQL injection defense), and transactions.",
        phase: "14-databases",
        order: 2,
        difficulty: "intermediate",
        prerequisites: ["relational-sql-fundamentals"],
        tags: ["sqlite", "parameterization", "transactions"],
        hasCode: true,
      },
      {
        slug: "postgresql-and-psycopg",
        title: "PostgreSQL & psycopg3 Driver",
        description: "Connection pooling, async drivers, and production database workflows.",
        phase: "14-databases",
        order: 3,
        difficulty: "intermediate",
        prerequisites: ["sqlite3-with-python"],
        tags: ["postgresql", "psycopg", "connection-pooling"],
        hasCode: true,
      },
      {
        slug: "sqlalchemy-orm-models",
        title: "SQLAlchemy 2.0 ORM & Declarative Models",
        description: "Mapped, mapped_column, relationships, and Session transactions.",
        phase: "14-databases",
        order: 4,
        difficulty: "intermediate",
        prerequisites: ["postgresql-and-psycopg"],
        tags: ["sqlalchemy", "orm", "models"],
        hasCode: true,
      },
      {
        slug: "database-migrations-alembic",
        title: "Database Migrations with Alembic",
        description: "Auto-generating migration scripts, revision history, and schema upgrades.",
        phase: "14-databases",
        order: 5,
        difficulty: "intermediate",
        prerequisites: ["sqlalchemy-orm-models"],
        tags: ["alembic", "migrations", "schema"],
        hasCode: true,
      },
    ],
  },

  /* ── 15. API DEVELOPMENT ───────────────────────────────────── */
  {
    slug: "15-api-development",
    title: "API Development",
    description: "HTTP, REST, JSON, authentication, and building APIs with Python.",
    order: 15,
    difficulty: "intermediate",
    lessons: [
      {
        slug: "http-protocol-and-rest",
        title: "HTTP Protocol & REST Architecture",
        description: "Status codes, HTTP methods, headers, body payloads, and idempotency.",
        phase: "15-api-development",
        order: 1,
        difficulty: "intermediate",
        prerequisites: ["database-migrations-alembic"],
        tags: ["http", "rest", "api", "status-codes"],
        hasCode: true,
      },
      {
        slug: "requests-and-httpx-clients",
        title: "Consuming APIs with requests & httpx",
        description: "Session management, retries, timeouts, and asynchronous HTTP client calls.",
        phase: "15-api-development",
        order: 2,
        difficulty: "intermediate",
        prerequisites: ["http-protocol-and-rest"],
        tags: ["requests", "httpx", "http-client"],
        hasCode: true,
      },
      {
        slug: "api-authentication-jwt",
        title: "API Authentication: API Keys & JWT",
        description: "Bearer tokens, JSON Web Token signatures, and header authorization.",
        phase: "15-api-development",
        order: 3,
        difficulty: "intermediate",
        prerequisites: ["requests-and-httpx-clients"],
        tags: ["auth", "jwt", "bearer", "security"],
        hasCode: true,
      },
      {
        slug: "pydantic-data-validation",
        title: "Data Validation with Pydantic v2",
        description: "BaseModel, Field constraints, model_validator, and JSON Schema generation.",
        phase: "15-api-development",
        order: 4,
        difficulty: "intermediate",
        prerequisites: ["api-authentication-jwt"],
        tags: ["pydantic", "validation", "schemas"],
        hasCode: true,
      },
    ],
  },

  /* ── 16. FASTAPI ───────────────────────────────────────────── */
  {
    slug: "16-fastapi",
    title: "FastAPI",
    description: "Build production-quality APIs with FastAPI, Pydantic, and OpenAPI.",
    order: 16,
    difficulty: "advanced",
    lessons: [
      {
        slug: "fastapi-getting-started",
        title: "FastAPI Routing & Path Operations",
        description: "Path parameters, query parameters, request bodies, and automatic OpenAPI docs.",
        phase: "16-fastapi",
        order: 1,
        difficulty: "advanced",
        prerequisites: ["pydantic-data-validation"],
        tags: ["fastapi", "routing", "openapi"],
        hasCode: true,
      },
      {
        slug: "fastapi-dependency-injection",
        title: "FastAPI Dependency Injection (Depends)",
        description: "Reusable database sessions, authentication guards, and yield dependencies.",
        phase: "16-fastapi",
        order: 2,
        difficulty: "advanced",
        prerequisites: ["fastapi-getting-started"],
        tags: ["fastapi", "depends", "dependency-injection"],
        hasCode: true,
      },
      {
        slug: "fastapi-async-and-background-tasks",
        title: "Async Endpoints & BackgroundTasks",
        description: "async def route handlers, concurrency, and offloading background jobs.",
        phase: "16-fastapi",
        order: 3,
        difficulty: "advanced",
        prerequisites: ["fastapi-dependency-injection"],
        tags: ["fastapi", "async", "background-tasks"],
        hasCode: true,
      },
      {
        slug: "fastapi-production-deployment",
        title: "Deploying FastAPI with Uvicorn & Docker",
        description: "ASGI servers, worker processes, health endpoints, and Docker containers.",
        phase: "16-fastapi",
        order: 4,
        difficulty: "advanced",
        prerequisites: ["fastapi-async-and-background-tasks"],
        tags: ["uvicorn", "docker", "production"],
        hasCode: true,
      },
    ],
  },

  /* ── 17. AUTOMATION ────────────────────────────────────────── */
  {
    slug: "17-automation",
    title: "Automation",
    description: "Automate files, emails, web scraping, and build CLI tools.",
    order: 17,
    difficulty: "intermediate",
    lessons: [
      {
        slug: "filesystem-automation",
        title: "Filesystem & OS Automation with os/shutil",
        description: "Automating directory cleanup, file renaming, and archive compression.",
        phase: "17-automation",
        order: 1,
        difficulty: "intermediate",
        prerequisites: ["fastapi-production-deployment"],
        tags: ["automation", "os", "shutil", "scripts"],
        hasCode: true,
      },
      {
        slug: "web-scraping-beautifulsoup",
        title: "Web Scraping with BeautifulSoup & requests",
        description: "HTML parsing, CSS selectors, pagination scraping, and robots.txt.",
        phase: "17-automation",
        order: 2,
        difficulty: "intermediate",
        prerequisites: ["filesystem-automation"],
        tags: ["scraping", "beautifulsoup", "html"],
        hasCode: true,
      },
      {
        slug: "browser-automation-playwright",
        title: "Headless Browser Automation with Playwright",
        description: "Automating dynamic JavaScript pages, form submissions, and screenshots.",
        phase: "17-automation",
        order: 3,
        difficulty: "intermediate",
        prerequisites: ["web-scraping-beautifulsoup"],
        tags: ["playwright", "browser", "headless"],
        hasCode: true,
      },
      {
        slug: "cli-tools-with-typer",
        title: "Building Production CLI Tools with Typer",
        description: "Type-driven CLI commands, flags, arguments, and rich terminal output.",
        phase: "17-automation",
        order: 4,
        difficulty: "intermediate",
        prerequisites: ["browser-automation-playwright"],
        tags: ["cli", "typer", "terminal"],
        hasCode: true,
      },
    ],
  },

  /* ── 18. PYTHON FOR DATA ───────────────────────────────────── */
  {
    slug: "18-data-python",
    title: "Python for Data",
    description: "NumPy, Pandas, Matplotlib, and data analysis with Python.",
    order: 18,
    difficulty: "intermediate",
    lessons: [
      {
        slug: "numpy-arrays-and-vectorization",
        title: "NumPy Arrays & Vectorized Computing",
        description: "ndarray creation, broadcasting, universal functions, and C-contiguous memory.",
        phase: "18-data-python",
        order: 1,
        difficulty: "intermediate",
        prerequisites: ["cli-tools-with-typer"],
        tags: ["numpy", "arrays", "vectorization"],
        hasCode: true,
      },
      {
        slug: "pandas-dataframes-and-series",
        title: "Pandas DataFrames & Series",
        description: "Indexing, loc/iloc slicing, column selection, and CSV loading.",
        phase: "18-data-python",
        order: 2,
        difficulty: "intermediate",
        prerequisites: ["numpy-arrays-and-vectorization"],
        tags: ["pandas", "dataframe", "series"],
        hasCode: true,
      },
      {
        slug: "data-cleaning-and-groupby",
        title: "Data Cleaning, Aggregation & GroupBy",
        description: "Handling missing data (dropna/fillna), apply(), and split-apply-combine.",
        phase: "18-data-python",
        order: 3,
        difficulty: "intermediate",
        prerequisites: ["pandas-dataframes-and-series"],
        tags: ["cleaning", "groupby", "aggregation"],
        hasCode: true,
      },
      {
        slug: "data-visualization-matplotlib-seaborn",
        title: "Data Visualization: Matplotlib & Seaborn",
        description: "Line plots, bar charts, histograms, heatmaps, and publication styling.",
        phase: "18-data-python",
        order: 4,
        difficulty: "intermediate",
        prerequisites: ["data-cleaning-and-groupby"],
        tags: ["matplotlib", "seaborn", "visualization"],
        hasCode: true,
      },
    ],
  },

  /* ── 19. ASYNC PYTHON ──────────────────────────────────────── */
  {
    slug: "19-asynchronous-python",
    title: "Async Python",
    description: "asyncio, threading, multiprocessing, and concurrent programming.",
    order: 19,
    difficulty: "advanced",
    lessons: [
      {
        slug: "asyncio-event-loop-coroutines",
        title: "asyncio: Event Loop & Coroutines",
        description: "async def, await, coroutine objects, and event loop scheduling.",
        phase: "19-asynchronous-python",
        order: 1,
        difficulty: "advanced",
        prerequisites: ["data-visualization-matplotlib-seaborn"],
        tags: ["asyncio", "coroutines", "event-loop"],
        hasCode: true,
      },
      {
        slug: "asyncio-gather-and-tasks",
        title: "Concurrent Execution: gather() & TaskGroup",
        description: "Running I/O tasks concurrently, cancellation, and Python 3.11+ TaskGroup.",
        phase: "19-asynchronous-python",
        order: 2,
        difficulty: "advanced",
        prerequisites: ["asyncio-event-loop-coroutines"],
        tags: ["gather", "taskgroup", "concurrency"],
        hasCode: true,
      },
      {
        slug: "threading-vs-multiprocessing",
        title: "Threading vs Multiprocessing in Python",
        description: "I/O bound vs CPU bound concurrency and bypassing the GIL.",
        phase: "19-asynchronous-python",
        order: 3,
        difficulty: "advanced",
        prerequisites: ["asyncio-gather-and-tasks"],
        tags: ["threading", "multiprocessing", "gil"],
        hasCode: true,
      },
      {
        slug: "concurrent-futures-and-queues",
        title: "ThreadPoolExecutor & ProcessPoolExecutor",
        description: "Managing worker pools, async queues (asyncio.Queue), and backpressure.",
        phase: "19-asynchronous-python",
        order: 4,
        difficulty: "advanced",
        prerequisites: ["threading-vs-multiprocessing"],
        tags: ["executors", "queues", "worker-pools"],
        hasCode: true,
      },
    ],
  },

  /* ── 20. REAL-WORLD PROJECTS ───────────────────────────────── */
  {
    slug: "20-real-world-projects",
    title: "Real-World Projects",
    description: "Build complete, production-quality Python applications.",
    order: 20,
    difficulty: "advanced",
    lessons: [
      {
        slug: "project-fullstack-fastapi-service",
        title: "Production REST API with FastAPI & SQLAlchemy",
        description: "Building an enterprise CRUD microservice with JWT auth and Postgres.",
        phase: "20-real-world-projects",
        order: 1,
        difficulty: "advanced",
        prerequisites: ["concurrent-futures-and-queues"],
        tags: ["capstone", "fastapi", "sqlalchemy", "postgres"],
        hasCode: true,
      },
      {
        slug: "project-distributed-task-worker",
        title: "Distributed Asynchronous Job Worker",
        description: "Building a Redis-backed queue worker handling background tasks.",
        phase: "20-real-world-projects",
        order: 2,
        difficulty: "advanced",
        prerequisites: ["project-fullstack-fastapi-service"],
        tags: ["capstone", "redis", "worker", "queues"],
        hasCode: true,
      },
      {
        slug: "project-realtime-websocket-engine",
        title: "Real-Time WebSocket Communication Server",
        description: "Building a bi-directional streaming server with pub/sub architecture.",
        phase: "20-real-world-projects",
        order: 3,
        difficulty: "advanced",
        prerequisites: ["project-distributed-task-worker"],
        tags: ["capstone", "websockets", "realtime", "streaming"],
        hasCode: true,
      },
      {
        slug: "project-production-microservice-docker",
        title: "Production Microservice Deployment & CI/CD",
        description: "Packaging Python services with multi-stage Docker builds and automated tests.",
        phase: "20-real-world-projects",
        order: 4,
        difficulty: "advanced",
        prerequisites: ["project-realtime-websocket-engine"],
        tags: ["capstone", "docker", "cicd", "production"],
        hasCode: true,
      },
    ],
  },
];

export const EXERCISES: Exercise[] = [
  {
    slug: "hello-world",
    title: "Hello, World!",
    description: "Print Hello, World! to the terminal.",
    difficulty: "beginner",
    tags: ["print", "basics"],
    hints: ["Use the print() function"],
  },
  {
    slug: "sum-two-numbers",
    title: "Sum of Two Numbers",
    description: "Return the sum of two numbers.",
    difficulty: "beginner",
    tags: ["arithmetic", "functions"],
    hints: ["Use the + operator"],
  },
  {
    slug: "even-or-odd",
    title: "Even or Odd",
    description: 'Return "even" or "odd" for a given integer.',
    difficulty: "beginner",
    tags: ["modulo", "conditionals"],
    hints: ["Use the % operator"],
  },
  {
    slug: "reverse-string",
    title: "Reverse a String",
    description: "Return the reverse of a given string.",
    difficulty: "easy",
    tags: ["strings", "slicing"],
    hints: ["Python slicing supports a step of -1"],
  },
  {
    slug: "fizzbuzz",
    title: "FizzBuzz",
    description: "Classic FizzBuzz for numbers 1 through n.",
    difficulty: "easy",
    tags: ["loops", "conditionals", "modulo"],
    hints: ["Check divisibility by 15 first"],
  },
  {
    slug: "two-sum",
    title: "Two Sum",
    description: "Find two indices that add up to a target value.",
    difficulty: "interview",
    tags: ["hash-map", "arrays", "interview"],
    hints: ["A hash map gives O(n) time complexity"],
  },
];

export const PROJECTS: Project[] = [
  {
    slug: "01-number-guessing-game",
    title: "Number Guessing Game",
    description: "A CLI game where the player guesses a random number.",
    difficulty: "beginner",
    concepts: ["variables", "loops", "conditionals", "random", "input"],
    order: 1,
  },
  {
    slug: "02-cli-task-manager",
    title: "CLI Task Manager",
    description: "A task manager storing structured tasks in JSON files.",
    difficulty: "intermediate",
    concepts: ["json", "file-handling", "classes", "typer"],
    order: 2,
  },
  {
    slug: "03-fastapi-crud-service",
    title: "Production REST API",
    description: "A full FastAPI REST service with SQLAlchemy ORM and SQLite.",
    difficulty: "advanced",
    concepts: ["fastapi", "sqlalchemy", "pydantic", "jwt"],
    order: 3,
  },
];

// Derived counts — calculated automatically from central dataset
export const STATS = {
  phases: PHASES.length,
  lessons: PHASES.reduce((acc, p) => acc + p.lessons.length, 0),
  exercises: EXERCISES.length,
  projects: PROJECTS.length,
};
